### ISSUE TITLE
Missing call to setgroups before setuid (rpmlint warning)

### ISSUE THREAD

**Issue by TC01** [ammongit/qotd#11]
Hi,

I was interested in making a Fedora package of qotd. The Fedora package checker tool, rpmlint, complains about the following:

```
$ rpmlint -i ../RPMS/x86_64/qotd-0.11.0-1.fc25.x86_64.rpm 
qotd.x86_64: E: missing-call-to-setgroups-before-setuid /usr/bin/qotdd
This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.
```

I figured I should at least report this upstream. My guess is setgroups should be called alongside setgid, but I'm not entirely sure.

(As a side note, where would you prefer to have issues reported-- here or gitlab?)

**Comment by ammongit** [comment]
TIL about `setgroups()`. I'll add this to the security relinquishment routine.
Also, yes this is the correct place to create issues. Thanks for bringing this to my attention.

**Comment by ammongit** [comment]
Also can you link me to where the RPM can be found? I'd like to add it to the README.

**Comment by ammongit** [comment]
Added in b68fde693b16bf2d.
