### ISSUE TITLE
Fedora packages for qotd

### ISSUE THREAD

**Issue by TC01** [ammongit/qotd#12]
Hey, sorry for the delay in responding to your question [here](https://github.com/ammongit/qotd/issues/11).

qotd was just accepted into the Fedora repositories. It'll take a while to propagate through (about a week) but after that users on Fedora 25+ and RHEL 7 should be able to just do:

```
dnf install qotd
```

And it'll install, if you want to mention that in the README. :)

**Comment by ammongit** [comment]
Nice! Thanks for doing this.

**Comment by ammongit** [comment]
The package includes the systemd service files, correct?

**Comment by TC01** [comment]
No problem!

Yes, the systemd service file is included.

**Comment by ammongit** [comment]
Added to the README.
